backend_application_port: 8032 # must be unique for each project on the same server
frontend_application_port: 3002 # must be unique for each project on the same server
environment_suffix: "_preprod"
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

main_hostname: "preprod-carte.iarbre.fr"
public_hostnames:
  - "{{ main_hostname }}"

showcase_hostname: "preprod-showcase.iarbre.fr"
showcase_redirect_hostnames: []
hugo_build_flags: "--buildDrafts --buildFuture --buildExpired"
use_password: true

# hostnames mentioned here are redirected to the main hostname
redirect_hostnames: []
all_hostnames: "{{ public_hostnames + redirect_hostnames }}"

project_dir: "{{project_base_dir}}{{ environment_suffix }}"
backend_static_path: "{{ project_dir }}/backend_static"

frontend_branch: dev
backend_branch: dev
showcase_branch: dev
docs_branch: dev

environment_name: production
