- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ project_slug }}-showcase
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: check if hugo is installed
  stat:
    path: /etc/{{ organization_slug }}/hugo_installed
  register: hugo_installed

- name: install hugo from URL
  get_url:
    url: "https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_linux-amd64.deb"
    dest: "/tmp/hugo.deb"
    mode: 0644
  when: not hugo_installed.stat.exists

- name: install hugo
  apt:
    deb: "/tmp/hugo.deb"
  become: yes
  when: not hugo_installed.stat.exists

- name: create hugo installed file
  file:
    path: /etc/{{ organization_slug }}/hugo_installed
    state: touch
  when: not hugo_installed.stat.exists

- name: Get or update showcase code
  shell: |
    if [ -d "{{ showcase_path }}/.git" ]; then
      cd "{{ showcase_path }}" && git fetch origin && git reset --hard origin/"{{ showcase_branch }}" && git submodule update --init --recursive
    else
      rm -rf "{{ showcase_path }}" && git clone --origin origin --branch "{{ showcase_branch }}" --recursive "{{ frontend_repo }}" "{{ showcase_path }}"
    fi
  args:
    executable: /bin/bash
  environment:
    GIT_SSH_COMMAND: "ssh -i {{ backend_identity_file_path }} -o StrictHostKeyChecking=no"
  become_user: "{{ main_user }}"
  register: clonecode
  changed_when: true

- name: Build showcase code for static rendering
  # yamllint disable-line rule:line-length
  shell: "hugo build"
  args:
    chdir: "{{ showcase_path }}"
    executable: /bin/bash
  when: clonecode.changed or force_update is defined
  register: build_code

- name: Update showcase static folder
  file:
    path: "{{ showcase_static_path }}"
    state: "{{ item }}"
    owner: www-data
    mode: "2755"
  with_items:
    - absent
    - directory
  when: clonecode.changed or force_update is defined

- name: update showcase static folder content
  synchronize:
    src: "{{ showcase_path }}/public/"
    dest: "{{ showcase_static_path }}/"
    rsync_opts:
      - "-og"
      - "--chown=www-data"
  delegate_to: "{{ inventory_hostname }}"
  when: clonecode.changed or force_update is defined
