- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ project_slug }}-showcase
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: check if hugo is installed
  stat:
    path: /etc/{{ organization_slug }}/hugo_installed
  register: hugo_installed

- name: install hugo from URL
  get_url:
    url: "https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_linux-amd64.deb"
    dest: "/tmp/hugo.deb"
    mode: 0644
  when: not hugo_installed.stat.exists

- name: install hugo
  apt:
    deb: "/tmp/hugo.deb"
  become: yes
  when: not hugo_installed.stat.exists

- name: create hugo installed file
  file:
    path: /etc/{{ organization_slug }}/hugo_installed
    state: touch
  when: not hugo_installed.stat.exists

- name: get latest showcase code
  git:
    repo: "{{ frontend_repo }}"
    dest: "{{ showcase_path }}/.."
    key_file: "{{ backend_identity_file_path }}"
    accept_hostkey: true
    force: true
    version: "{{ showcase_branch }}"
    # git submodule should have master branch
    track_submodules: true
    remote: origin
  become_user: "{{ main_user }}"
  register: clonecode

- name: Build showcase code for static rendering
  # yamllint disable-line rule:line-length
  shell: "hugo build {{ hugo_build_flags }}"
  args:
    chdir: "{{ showcase_path }}"
    executable: /bin/bash
  when: clonecode.changed or force_update is defined
  register: build_code

- name: Update showcase static folder
  file:
    path: "{{ showcase_static_path }}"
    state: "{{ item }}"
    owner: www-data
    mode: "2755"
  with_items:
    - absent
    - directory
  when: clonecode.changed or force_update is defined

- name: update showcase static folder content
  synchronize:
    src: "{{ showcase_path }}/public/"
    dest: "{{ showcase_static_path }}/"
    rsync_opts:
      - "-og"
      - "--chown=www-data"
  delegate_to: "{{ inventory_hostname }}"
  when: clonecode.changed or force_update is defined
