# Generated by Django 5.1.3 on 2024-12-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0005_alter_mvttile_mvt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tilefactor",
            name="tile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factors",
                to="iarbre_data.tile",
            ),
        ),
    ]
