# Generated by Django 5.1.3 on 2025-01-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iarbre_data",
            "0008_iris_remove_city_insee_code_city_code_tile_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="iris",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irises",
                to="iarbre_data.city",
            ),
        ),
    ]
