# Generated by Django 5.1.3 on 2025-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0009_iris_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
