# Generated by Django 5.1.3 on 2025-01-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0012_city_tiles_computed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tile",
            old_name="indice",
            new_name="plantability_indice",
        ),
        migrations.RenameField(
            model_name="tile",
            old_name="normalized_indice",
            new_name="plantability_normalized_indice",
        ),
    ]
