# Generated by Django 5.1.5 on 2025-02-21 10:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0013_rename_indice_tile_plantability_indice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lcz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=2154),
                ),
                (
                    "map_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                ("lcz_indice", models.CharField(max_length=4, null=True)),
                ("lcz_description", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
