# Generated by Django 5.1.5 on 2025-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0013_rename_indice_tile_plantability_indice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvttile",
            name="layer",
            field=models.CharField(default="plantability", max_length=50),
        ),
    ]
