# Generated by Django 5.1.5 on 2025-03-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0014_lcz"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvttile",
            name="layer",
            field=models.CharField(default="plantability", max_length=50),
        ),
    ]
