# Generated by Django 5.1.5 on 2025-03-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0015_mvttile_layer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lcz",
            old_name="lcz_indice",
            new_name="lcz_index",
        ),
    ]
