# Generated by Django 5.1.5 on 2025-03-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0016_rename_lcz_indice_lcz_lcz_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mvttile",
            old_name="layer",
            new_name="datatype",
        ),
        migrations.RenameField(
            model_name="mvttile",
            old_name="model_type",
            new_name="geolevel",
        ),
    ]
