# Generated by Django 5.1.5 on 2025-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0017_rename_layer_mvttile_datatype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[("lcz", "LCZ"), ("plantability", "Plantability")],
                default="plantability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="geolevel",
            field=models.CharField(
                choices=[
                    ("tile", "Tile"),
                    ("city", "City"),
                    ("iris", "Iris"),
                    ("lcz", "LCZ"),
                ],
                max_length=50,
            ),
        ),
    ]
