# Generated by Django 5.1.5 on 2025-03-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0014_feedback"),
        ("iarbre_data", "0017_rename_layer_mvttile_datatype_and_more"),
    ]

    operations = []
