# Generated by Django 5.1.7 on 2025-03-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0020_vulnerability_alter_mvttile_datatype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
