# Generated by Django 5.2 on 2025-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0022_lcz_details_tile_details_vulnerability_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="meta_factors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
