# Generated by Django 5.2.2 on 2025-06-13 09:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0023_tile_meta_factors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="geolevel",
            field=models.CharField(
                choices=[
                    ("tile", "Tile"),
                    ("city", "City"),
                    ("iris", "Iris"),
                    ("lcz", "LCZ"),
                    ("cadastre", "Cadastre"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Cadastre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=2154),
                ),
                (
                    "map_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                ("parcel_id", models.CharField(max_length=50, unique=True)),
                ("commune_code", models.CharField(max_length=10)),
                (
                    "commune_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                ("surface", models.IntegerField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadastres",
                        to="iarbre_data.city",
                    ),
                ),
            ],
        ),
    ]
