# Generated by Django 5.2.2 on 2025-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0026_hotspot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotspot",
            name="city_name",
            field=models.CharField(max_length=200),
        ),
    ]
