# Generated by Django 5.2.2 on 2025-08-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0027_alter_hotspot_city_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotspot",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotspot",
                to="iarbre_data.city",
            ),
        ),
    ]
