# Generated by Django 5.2.2 on 2025-10-10 14:03

import iarbre_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0030_alter_tile_vulnerability_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="plantability_counts",
            field=models.JSONField(
                default=iarbre_data.models.default_plantability_counts
            ),
        ),
        migrations.AddField(
            model_name="iris",
            name="plantability_counts",
            field=models.JSONField(
                default=iarbre_data.models.default_plantability_counts
            ),
        ),
    ]
