# Generated by Django 5.2.9 on 2026-01-07 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0031_city_plantability_counts_iris_plantability_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiosphereFunctionalIntegrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=2154)),
                (
                    "map_geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    ("BiosphereIntegrity", "Biosphere Functional Integrity"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="geolevel",
            field=models.CharField(
                choices=[
                    ("tile", "Tile"),
                    ("city", "City"),
                    ("iris", "Iris"),
                    ("lcz", "LCZ"),
                    ("cadastre", "Cadastre"),
                    ("BiosphereIntegrity", "Biosphere Functional Integrity"),
                ],
                max_length=50,
            ),
        ),
    ]
