# Generated by Django 5.2.2 on 2025-10-21 09:49

import iarbre_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0031_city_plantability_counts_iris_plantability_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="plantability_counts",
            field=models.JSONField(
                default=iarbre_data.models.default_plantability_counts
            ),
        ),
        migrations.AlterField(
            model_name="iris",
            name="plantability_counts",
            field=models.JSONField(
                default=iarbre_data.models.default_plantability_counts
            ),
        ),
    ]
