# Generated by Django 5.2.7 on 2025-12-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0031_city_plantability_counts_iris_plantability_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    ("vegetation", "Vegetation"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
    ]
