# Generated by Django 5.2.7 on 2025-12-22 11:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0032_alter_mvttile_datatype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vegestrate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=2154),
                ),
                (
                    "map_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "strate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("arbustif", "Arbustif"),
                            ("arborescent", "Arborescent"),
                            ("herbacee", "Herbacée"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("surface", models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="vegetation_voirie_basse",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="vegetation_voirie_haute",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="vegetation_voirie_moyenne",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="vegetation_voirie_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    ("vegetation", "Vegetation"),
                    ("vegestrate", "Vegestrate"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
    ]
