# Generated by Django 5.2.7 on 2026-01-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0032_alter_mvttile_datatype"),
        ("iarbre_data", "0032_alter_tile_vulnerability_idx"),
    ]

    operations = []
