# Generated by Django 5.2.9 on 2026-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iarbre_data",
            "0032_biospherefunctionalintegrity_alter_mvttile_datatype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="biospherefunctionalintegrity",
            name="index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
