# Generated by Django 5.2.7 on 2025-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0032_ipave_city_vegetation_voirie_basse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    ("ipave", "Ipave"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
    ]
