# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0033_biospherefunctionalintegrity_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biospherefunctionalintegrity",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=2154),
        ),
        migrations.AlterField(
            model_name="biospherefunctionalintegrity",
            name="map_geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=3857
            ),
        ),
    ]
