# Generated by Django 5.2.7 on 2026-01-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0032_alter_tile_vulnerability_idx"),
        ("iarbre_data", "0033_vegestrate_city_vegetation_voirie_basse_and_more"),
    ]

    operations = []
