# Generated by Django 5.2.9 on 2026-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0034_alter_biospherefunctionalintegrity_geometry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biospherefunctionalintegrity",
            old_name="index",
            new_name="indice",
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    (
                        "biosphere_functional_integrity",
                        "Biosphere Functional Integrity",
                    ),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="geolevel",
            field=models.CharField(
                choices=[
                    ("tile", "Tile"),
                    ("city", "City"),
                    ("iris", "Iris"),
                    ("lcz", "LCZ"),
                    ("cadastre", "Cadastre"),
                    (
                        "biosphere_functional_integrity",
                        "Biosphere Functional Integrity",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
