# Generated by Django 5.2.7 on 2026-02-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0033_merge_20260121_0809"),
        ("iarbre_data", "0034_merge_20260121_0813"),
    ]

    operations = []
