# Generated by Django 5.2.7 on 2026-02-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0035_merge_20260203_1020"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="vegetation_voirie_basse",
            new_name="bushes_surface",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="vegetation_voirie_haute",
            new_name="grass_surface",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="vegetation_voirie_moyenne",
            new_name="total_vegetation_surface",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="vegetation_voirie_total",
            new_name="trees_surface",
        ),
    ]
