# Generated by Django 5.2.9 on 2026-01-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0033_merge_20260121_0809"),
        (
            "iarbre_data",
            "0035_rename_index_biospherefunctionalintegrity_indice_and_more",
        ),
    ]

    operations = []
