# Generated by Django 5.2.11 on 2026-02-17 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iarbre_data",
            "0036_rename_vegetation_voirie_basse_city_bushes_surface_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BiosphereFunctionalIntegrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=2154),
                ),
                (
                    "map_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                ("indice", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    (
                        "biosphere_functional_integrity",
                        "Biosphere Functional Integrity",
                    ),
                    ("vegetation", "Vegetation"),
                    ("vegestrate", "Vegestrate"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mvttile",
            name="geolevel",
            field=models.CharField(
                choices=[
                    ("tile", "Tile"),
                    ("city", "City"),
                    ("iris", "Iris"),
                    ("lcz", "LCZ"),
                    ("cadastre", "Cadastre"),
                    (
                        "biosphere_functional_integrity",
                        "Biosphere Functional Integrity",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
