# Generated by Django 5.2.9 on 2026-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iarbre_data",
            "0036_rename_vegetation_voirie_basse_city_bushes_surface_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vegestrate",
            index=models.Index(
                fields=["strate", "surface"], name="vegestrate_strate_surface_idx"
            ),
        ),
    ]
