# Generated by Django 5.2.7 on 2026-02-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0037_vegestrate_strate_surface_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HotSpot",
        ),
    ]
