# Generated by Django 5.2.7 on 2026-03-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0038_delete_hotspot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    ("vegestrate", "Vegestrate"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
    ]
