# Generated by Django 5.2.12 on 2026-03-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "iarbre_data",
            "0037_biospherefunctionalintegrity_alter_mvttile_datatype_and_more",
        ),
        ("iarbre_data", "0039_alter_mvttile_datatype"),
    ]

    operations = []
