# Generated by Django 5.2.12 on 2026-04-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0039_alter_mvttile_datatype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("lcz", "LCZ"),
                    ("plantability", "Plantability"),
                    ("vulnerability", "Vulnerability"),
                    ("cadastre", "Cadastre"),
                    ("vegestrate", "Vegestrate"),
                    ("soil_occupancy", "Soil occupancy"),
                ],
                default="plantability",
                max_length=50,
            ),
        ),
    ]
