# Generated by Django 5.2.12 on 2026-04-02 13:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0040_merge_20260331_1325"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiosphereFunctionalIntegrityLandCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=2154),
                ),
                (
                    "map_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "land_cover",
                    models.CharField(
                        choices=[
                            ("batiment", "Bâtiment"),
                            ("zone_permeable", "Zone perméable"),
                            ("zone_impermeable", "Zone imperméable"),
                            ("piscine", "Piscine"),
                            ("sol_nu", "Sol nu"),
                            ("surface_eau", "Surface eau"),
                            ("neige", "Neige"),
                            ("conifere", "Conifère"),
                            ("feuillu", "Feuillu"),
                            ("broussaille", "Broussaille"),
                            ("vigne", "Vigne"),
                            ("pelouse_urbaine", "Pelouse urbaine"),
                            ("culture", "Culture"),
                            ("terre_labouree", "Terre labourée"),
                            ("serre", "Serre"),
                            ("plantation_arbres", "Plantation d'arbres"),
                            ("paturage", "Pâturage"),
                            ("prairie_naturelle", "Prairie naturelle"),
                            ("fourre", "Fourré"),
                        ],
                        max_length=50,
                    ),
                ),
                ("binary", models.BooleanField(null=True)),
            ],
        ),
    ]
