# Generated by Django 5.2.14 on 2026-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0041_biosphere_land_cover_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="meta_factors_avg",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iris",
            name="meta_factors_avg",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
