# Generated by Django 5.2.16 on 2026-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0042_add_meta_factors_avg_to_city_iris"),
    ]

    operations = [
        migrations.AddField(
            model_name="vegestrate",
            name="mean_height",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
