---
- name: Setup docs on prod only
  hosts: prod
  vars:
    main_hostname: "docs.iarbre.fr"
    docs_static_path: "{{ project_dir }}/docs_static"
    mkdocs_path: "{{ project_dir }}/docs"
    venv:
      path: /usr/local/{{ organization_slug }}/{{ project_slug }}/docs/venv
  handlers:
    - import_tasks: telescoop-deploy/handlers/nginx.yml
  tasks:
    - import_tasks: telescoop-deploy/tasks/create-https-certificate.yml
    - import_tasks: telescoop-deploy/tasks/setup-user-and-directories.yml
    - import_tasks: telescoop-deploy/tasks/setup-and-clone-git.yml
      vars:
        repo: "{{ backend_repo }}"
        clone_path: "{{ mkdocs_path }}"
        branch: "{{ docs_branch }}"
        git_track_submodules: false
        identity_file_path: "{{ backend_identity_file_path }}"
    - import_tasks: telescoop-deploy/tasks/install-python-venv.yml
      vars:
        requirements: "{{ mkdocs_path }}/mkdocs-requirements.txt"
    - import_tasks: telescoop-deploy/tasks/build-mkdocs.yml
      vars:
        mkdocs_static_path: "{{ docs_static_path }}"
    - import_tasks: telescoop-deploy/tasks/setup-nginx.yml
      vars:
        nginx_conf_filename: "{{ project_slug }}-docs"
        static_path: "{{ docs_static_path }}"
