# Setup nginx for static website
# support http authentication
#
# Required vars:
#  - use_password
#  - username and passsword if use_password is set
#  - project_slug
#  - redirect_hostnames
#  - certificate_hostname
#  - static_path
---
- name: Install passlib python package, required by community.general.htpasswd
  ansible.builtin.apt:
    name:
      - python3-passlib
  when: use_password == true

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: "{{ project_dir }}/passwdfile"
    name: "{{ username }}"
    password: "{{ password }}"
    group: www-data
    mode: 0640
  when: use_password == true

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ project_slug }}
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
