# Generated by Django 5.1 on 2024-08-16 20:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=2154),
        ),
        migrations.AlterField(
            model_name="data",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=2154),
        ),
        migrations.AlterField(
            model_name="tile",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=2154),
        ),
    ]
