# Generated by Django 5.1 on 2024-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tile_images/"),
        ),
    ]
