# Generated by Django 5.1.3 on 2024-12-05 13:39

import django.contrib.gis.db.models.fields
from django.db import migrations
from tqdm import tqdm


def add_map_geometry(apps, _):
    Tile = apps.get_model("iarbre_data", "Tile")
    tiles_to_add = []

    tiles = Tile.objects.all()
    for tile in tqdm(tiles, desc="Adding map geometry", total=len(tiles)):
        tile.map_geometry = tile.geometry.transform(3857, clone=True)
        tiles_to_add.append(tile)

    Tile.objects.bulk_update(tiles_to_add, ["map_geometry"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="map_geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                null=True, srid=3857
            ),
        ),
        migrations.RunPython(add_map_geometry, migrations.RunPython.noop),
    ]
