# Generated by Django 5.1.3 on 2024-12-17 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0002_tile_map_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="normalized_indice",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tile",
            name="map_geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=3857
            ),
        ),
    ]
