# Generated by Django 5.1 on 2024-08-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0002_alter_city_geometry_alter_data_geometry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tile",
            name="indice",
            field=models.FloatField(null=True),
        ),
    ]
