# Generated by Django 5.1 on 2024-11-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0002_tile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tile",
            name="image",
        ),
    ]
