# Generated by Django 5.1.3 on 2024-12-20 09:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0003_tile_normalized_indice_alter_tile_map_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVTTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zoom_level", models.IntegerField()),
                ("tile_x", models.IntegerField()),
                ("tile_y", models.IntegerField()),
                ("model_type", models.CharField(max_length=50)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=3857),
                ),
                ("mvt_file", models.FileField(upload_to="tiles/")),
            ],
        ),
    ]
