# Generated by Django 5.1 on 2024-10-08 06:51

from django.db import migrations


def transform_geometry_srid(apps, schema_editor):
    # List of models and their app name
    models_to_transform = ["Tile", "Data", "City"]
    app_name = "iarbre_data"

    for model_name in models_to_transform:
        Model = apps.get_model(app_name, model_name)
        # Loop through each object in the model and transform its geometry SRID if needed
        for obj in Model.objects.all():
            if obj.geometry.srid == 2154:  # Check if geometry is in SRID 2154
                obj.geometry.transform(3857)  # Transform to SRID 3857
                obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iarbre_data", "0004_tilefactor"),
    ]

    operations = [
        migrations.RunPython(transform_geometry_srid),
    ]

