# Generated by Django 5.1 on 2024-10-08 06:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0004_tilefactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tile",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
    ]
