# Generated by Django 5.1.3 on 2024-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0004_mvttile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvttile",
            name="mvt_file",
            field=models.FileField(upload_to="mvt_files/"),
        ),
    ]
