# Generated by Django 5.1.3 on 2025-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0010_alter_city_name_alter_iris_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="tiles_generated",
            field=models.BooleanField(default=False),
        ),
    ]
