# Generated by Django 5.1.3 on 2025-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iarbre_data", "0011_city_tiles_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="tiles_computed",
            field=models.BooleanField(default=False),
        ),
    ]
