/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CircularProgress: typeof import('./src/components/progress/CircularProgress.vue')['default']
    ClimateZoneScorePopupContent: typeof import('./src/components/map/popup/ClimateZoneScorePopupContent.vue')['default']
    ClimateZonesLegend: typeof import('./src/components/map/legend/ClimateZonesLegend.vue')['default']
    EmptyMessage: typeof import('./src/components/EmptyMessage.vue')['default']
    FeedbackForm: typeof import('./src/components/forms/FeedbackForm.vue')['default']
    FeedbackPopin: typeof import('./src/components/FeedbackPopin.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayerSwitcher: typeof import('./src/components/layerSwitcher/LayerSwitcher.vue')['default']
    MapBgSwitcher: typeof import('./src/components/mapSwitcher/MapBgSwitcher.vue')['default']
    MapComponent: typeof import('./src/components/map/MapComponent.vue')['default']
    MapContextData: typeof import('./src/components/contextData/MapContextData.vue')['default']
    MapContextDataPlantability: typeof import('./src/components/contextData/MapContextDataPlantability.vue')['default']
    MapContextDataVulnerability: typeof import('./src/components/contextData/MapContextDataVulnerability.vue')['default']
    MapContextHeader: typeof import('./src/components/contextData/MapContextHeader.vue')['default']
    MapContextTools: typeof import('./src/components/contextTools/MapContextTools.vue')['default']
    MapLayerSwitcher: typeof import('./src/components/layerSwitcher/MapLayerSwitcher.vue')['default']
    MapLegend: typeof import('./src/components/map/legend/MapLegend.vue')['default']
    MapScorePopup: typeof import('./src/components/map/popup/MapScorePopup.vue')['default']
    MapSwitcher: typeof import('./src/components/mapSwitcher/MapSwitcher.vue')['default']
    NavbarComponent: typeof import('./src/components/navbar/NavbarComponent.vue')['default']
    PlantabilityContextDataAccordionItem: typeof import('./src/components/contextData/plantability/PlantabilityContextDataAccordionItem.vue')['default']
    PlantabilityContextDataItem: typeof import('./src/components/contextData/plantability/PlantabilityContextDataItem.vue')['default']
    PlantabilityContextDataList: typeof import('./src/components/contextData/plantability/PlantabilityContextDataList.vue')['default']
    PlantabilityContextDataScore: typeof import('./src/components/contextData/plantability/PlantabilityContextDataScore.vue')['default']
    PlantabilityLegend: typeof import('./src/components/map/legend/PlantabilityLegend.vue')['default']
    PlantabilityScorePopupContent: typeof import('./src/components/map/popup/PlantabilityScorePopupContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreLabel: typeof import('./src/components/map/ScoreLabel.vue')['default']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    VulnerabilityContexDataTableRow: typeof import('./src/components/contextData/vulnerability/VulnerabilityContexDataTableRow.vue')['default']
    VulnerabilityContextDataLegend: typeof import('./src/components/contextData/vulnerability/VulnerabilityContextDataLegend.vue')['default']
    VulnerabilityContextDataScore: typeof import('./src/components/contextData/vulnerability/VulnerabilityContextDataScore.vue')['default']
    VulnerabilityContextDataScoreBadge: typeof import('./src/components/contextData/vulnerability/VulnerabilityContextDataScoreBadge.vue')['default']
    VulnerabilityContextDataTable: typeof import('./src/components/contextData/vulnerability/VulnerabilityContextDataTable.vue')['default']
    VulnerabilityContextDataTableHeader: typeof import('./src/components/contextData/vulnerability/VulnerabilityContextDataTableHeader.vue')['default']
    VulnerabilityContextTool: typeof import('./src/components/contextTools/VulnerabilityContextTool.vue')['default']
    VulnerabilityLegend: typeof import('./src/components/map/legend/VulnerabilityLegend.vue')['default']
    VulnerabilityScorePopupContent: typeof import('./src/components/map/popup/VulnerabilityScorePopupContent.vue')['default']
    VulnerabilityScorePopupItem: typeof import('./src/components/map/popup/VulnerabilityScorePopupItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
