/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ClimateZoneScorePopupContent: typeof import('./src/components/map/popup/ClimateZoneScorePopupContent.vue')['default']
    ClimateZonesLegend: typeof import('./src/components/map/legend/ClimateZonesLegend.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import("primevue/divider")["default"]
    FeedbackForm: typeof import('./src/components/forms/FeedbackForm.vue')['default']
    FeedbackPopin: typeof import('./src/components/FeedbackPopin.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayerSwitcher: typeof import('./src/components/map/layerSwitcher/LayerSwitcher.vue')['default']
    MapComponent: typeof import('./src/components/map/MapComponent.vue')['default']
    MapContextTools: typeof import('./src/components/map/contextTools/MapContextTools.vue')['default']
    MapLayerSwitcher: typeof import('./src/components/map/layerSwitcher/MapLayerSwitcher.vue')['default']
    MapLegend: typeof import('./src/components/map/legend/MapLegend.vue')['default']
    MapScorePopup: typeof import('./src/components/map/popup/MapScorePopup.vue')['default']
    NavbarComponent: typeof import('./src/components/navbar/NavbarComponent.vue')['default']
    PlantabilityLegend: typeof import('./src/components/map/legend/PlantabilityLegend.vue')['default']
    PlantabilityScorePopupContent: typeof import('./src/components/map/popup/PlantabilityScorePopupContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreLabel: typeof import('./src/components/map/ScoreLabel.vue')['default']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    VulnerabilityContextTool: typeof import('./src/components/map/contextTools/VulnerabilityContextTool.vue')['default']
    VulnerabilityLegend: typeof import('./src/components/map/legend/VulnerabilityLegend.vue')['default']
    VulnerabilityScorePopupContent: typeof import('./src/components/map/popup/VulnerabilityScorePopupContent.vue')['default']
    VulnerabilityScorePopupItem: typeof import('./src/components/map/popup/VulnerabilityScorePopupItem.vue')['default']
  }
}
