organization_slug: telescoop
base_project_slug: iarbre
main_user: iarbre
main_user_uid: 10045 # TODO must be unique for each project on the server
django_project_name: iarbre_data
backend_repo: git@github.com:TelesCoop/iarbre.git
frontend_repo: git@github.com:TelesCoop/iarbre.git
backend_identity_file_path: /home/{{ main_user }}/.ssh/id_ed25519_backend
var_log_path: /var/log/{{ organization_slug }}/{{ project_slug }}
project_base_dir: /{{ organization_slug }}/{{ base_project_slug }}
supervisor_conf: /etc/supervisor/conf.d

requests_timeout: 30
# if using postgresql database, you will need to
# - define the var `database_password`
# - install an additional Ansible module `ansible-galaxy collection install community.postgresql`
database_provider: postgresql # sqlite or postgresql

# can be SSR or static
frontend_mode: static
