from pathlib import Path

import rasterio
from django.conf import settings
from django.http import FileResponse, Http404
from rest_framework.exceptions import ValidationError
from rest_framework.views import APIView

from heat.raster import hour_raster_path, is_up_to_date


def _entry(path: str, filename: str | None = None) -> tuple[str, str]:
    """Build a ``(path, filename)`` tuple, defaulting filename to basename."""
    return path, filename or Path(path).name


base_dir = "rasters/WMS/"
RASTER_MAP: dict[str, tuple[str, str]] = {
    "pet_index": _entry(base_dir + "PET_index.tif"),
    "sun_exposure": _entry(base_dir + "SunExposure.tif"),
}
HOURLY_RASTERS = {"pet_index"}


class FileDownloadView(APIView):
    """Base view for serving pre-generated static files from MEDIA_ROOT.

    Subclasses set ``file_map`` and ``download_content_type`` to configure
    which files are available and how they are served.
    """

    file_map: dict[str, tuple[str, str]] = {}
    download_content_type: str = "application/octet-stream"

    def get(self, request, file_key: str):
        if file_key not in self.file_map:
            available = ", ".join(self.file_map)
            raise Http404(f"Unknown key '{file_key}'. Available: {available}.")

        relative_path, filename = self.file_map[file_key]
        full_path = Path(settings.MEDIA_ROOT) / relative_path

        if not full_path.exists():
            raise Http404(f"File not found: {filename}.")

        return self._serve(full_path, filename)

    def _serve(self, full_path: Path, filename: str) -> FileResponse:
        response = FileResponse(
            full_path.open("rb"),
            content_type=self.download_content_type,
            as_attachment=True,
            filename=filename,
        )
        response["Cache-Control"] = "public, max-age=3600"
        return response


class RasterDownloadView(FileDownloadView):
    """Download raster files (GeoTIFF). Example: ``GET /api/rasters/sun_exposure/``.

    Hourly rasters (one band per hour, band = hour + 1) accept an ``hour``
    query parameter to download a single-band GeoTIFF for that hour:

        GET /api/rasters/pet_index/?hour=14

    Hour files are generated by ``python manage.py split_pet_index``.
    """

    file_map = RASTER_MAP
    download_content_type = "image/tiff"

    def get(self, request, file_key: str):
        if file_key in HOURLY_RASTERS and "hour" in request.query_params:
            return self._get_hour(file_key, request.query_params["hour"])
        return super().get(request, file_key)

    def _get_hour(self, file_key: str, hour_param: str):
        relative_path, filename = self.file_map[file_key]
        full_path = Path(settings.MEDIA_ROOT) / relative_path
        if not full_path.exists():
            raise Http404(f"File not found: {filename}.")

        with rasterio.open(full_path) as src:
            band_count = src.count
        try:
            hour = int(hour_param)
        except ValueError:
            raise ValidationError({"hour": "Must be an integer."})
        if not 0 <= hour < band_count:
            raise ValidationError({"hour": f"Must be between 0 and {band_count - 1}."})

        hour_path = hour_raster_path(full_path, hour)
        if not is_up_to_date(full_path, hour_path):
            raise Http404(f"File not found: {hour_path.name}.")
        return self._serve(hour_path, hour_path.name)
