name: CI tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
env:
  TELESCOOP_DEV: true
  IS_TESTING: true

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      # https://github.com/actions/setup-python/blob/main/README.md#caching-packages-dependencies
      - run: pip install -r back/requirements.txt

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}

      - name: Configure npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm config set fetch-retries 3
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
        working-directory: ./front

      - name: Install front js dependencies
        run: npm ci --prefer-offline --no-audit && npx allow-scripts
        working-directory: ./front

  pre-commit:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      # https://github.com/actions/setup-python/blob/main/README.md#caching-packages-dependencies
      - run: pip install -r back/requirements.txt

      - name: Set up PostGIS
        uses: nyurik/action-setup-postgis@v2
        with:
          username: myuser
          password: securepassword
          database: mydatabase
          port: 5432
        id: postgres

      - name: Create local_settings.ini
        run: |
          cat <<EOF > back/local_settings.ini
          [database]
          engine=postgresql
          user=myuser
          name=mydatabase
          password=securepassword
          EOF

      - name: Restore Node.js cache
        uses: actions/cache@v3
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}

      - name: Install js dependencies if not cached
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci && npx allow-scripts
        working-directory: ./front

      - name: Enforce pre-commit hook server side
        env:
          DATABASE_URL: "postgres://myuser:securepassword@localhost:5432/mydatabase"
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}
          SKIP: django-test
          # We are already running django-test just bellow : `Generate coverage report`
        uses: pre-commit/action@v3.0.1

      - name: Generate coverage report
        run: |
          cd back
          coverage run manage.py test
          coverage json --omit="*/migrations/*"
          COVERAGE=$(python3 -c "import json; print(int(json.load(open('coverage.json'))['totals']['percent_covered']))")
          echo "COVERAGE_PERCENT=$COVERAGE" >> $GITHUB_ENV

          # Choose badge color based on coverage percentage
          if (( $(echo "$COVERAGE >= 85" | bc -l) )); then
            echo "BADGE_COLOR=brightgreen" >> $GITHUB_ENV
          elif (( $(echo "$COVERAGE >= 75" | bc -l) )); then
            echo "BADGE_COLOR=yellow" >> $GITHUB_ENV
          else
            echo "BADGE_COLOR=red" >> $GITHUB_ENV
          fi

      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 86d9b33a236f4e03bca8799858fc7f6d
          filename: coverage-badge.json
          label: Backend coverage
          message: ${{ env.COVERAGE_PERCENT }}%
          color: ${{ env.BADGE_COLOR }}

  doc-tests:
    runs-on: ubuntu-22.04
    needs: [setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python doc
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r mkdocs-requirements.txt
      - name: Run documentation validation
        run: mkdocs build --strict
