name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, dev]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[no doc]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install -r requirements.txt  # If you have additional dependencies

      - name: Deploy doc
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: docs.yml
          directory: deploy
          vault_password: ${{secrets.ANSIBLE_VAULT_KEY}}
          options: |
            -l prod
          key: ${{ secrets.SSH_PRIVATE_KEY }}
