name: Build Documentation

on:
  push:
    branches:
      - dev
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[no doc]')"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy doc
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: docs.yml
          directory: deploy
          vault_password: ${{secrets.ANSIBLE_VAULT_KEY}}
          options: |
            -l prod
          key: ${{ secrets.SSH_PRIVATE_KEY }}
