name: TypeScript Lint

on:
  push:
    branches: [main, master]
  pull_request:
    
  workflow_dispatch:

jobs:
  lint:
    name: Run TypeScript Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "./front/.nvmrc"
          cache: "npm"
          cache-dependency-path: ./front/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      - name: Run Linter
        run: npm run lint
        working-directory: ./front
